### ISSUE TITLE
Any query to the parse server just hangs and never returns a response 

### ISSUE THREAD

**Issue by th3brink** [parse-community/Parse-SDK-Flutter#305]
I can run the curl response from the debug output, but any query from the Parse-SDK-Flutter, besides the await ParseUser.currentUser(),  just hangs. The Future never finishes, and there is no error or exception.

part of the main.dart file.
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Provider.debugCheckInvalidValueType = null;
  try {
    await Parse().initialize(
      PARSE_APP_ID,
      PARSE_APP_URL,
      masterKey: MASTER_KEY,
      // clientKey: CLIENT_KEY,
      // liveQueryUrl: LIVE_QUERY_URL,
      autoSendSessionId: true,
      // debug: true,
      coreStore: await CoreStoreSharedPrefsImp.getInstance(),
    );
    // print(parse.hasParseBeenInitialized());
  } catch (error) {
    print(error);
  }

  var user = await ParseUser.currentUser();  // Works for some random reason.

  runApp(MyApp(user));
}
```

The extended parse object.
```
import 'package:EarnIt/models/task.dart';
import 'package:flutter_hooks/flutter_hooks.dart';
import 'package:parse_server_sdk/parse_server_sdk.dart';

class Goal extends ParseObject implements ParseCloneable {
  List<Task> tasks = [];

  Goal() : super(_keyTableName);
  Goal.clone() : this();

  /// Looks strangely hacky but due to Flutter not using reflection, we have to
  /// mimic a clone
  @override
  clone(Map map) => Goal.clone()..fromJson(map);

  static const String _keyTableName = 'Goal';
  static const String keyName = 'name';
  static const String keyReward = 'reward';
  static const String keyDetails = 'details';

  String get objectId => get<String>('objectId');
  set objectId(String name) => set<String>('objectId', name);

  String get name => get<String>(keyName);
  set name(String name) => set<String>(keyName, name);

  String get reward => get<String>(keyReward);
  set reward(String name) => set<String>(keyReward, name);

  String get details => get<String>(keyDetails);
  set details(String name) => set<String>(keyDetails, name);

  DateTime get dueAt => get<DateTime>('dueAt');
  set dueAt(DateTime name) => set<DateTime>('dueAt', name);

  String get category => get<String>('category');
  set category(String name) => set<String>('category', name);

  bool get isDone => get<bool>('isDone');
  set isDone(bool name) => set<bool>('isDone', name);

  String get owner => get<String>('owner');
  set owner(String name) => set<String>('owner', name);

  // List get tasks => get<List>('tasks');
  // set tasks(List name) => set<List>('tasks', name);

  Future getTask() async {
    ParseResponse response =
        await (get('tasks') as ParseRelation<ParseObject>).getQuery().query();
    if (response.success && response.results != null) {
      tasks = response.results; // .map((item) => Task().clone(item)).toList();
    }
    tasks = [];
    return tasks;
  }

  Future<List<Goal>> getUserGoals() async {
    try {
      ParseUser user = await ParseUser.currentUser() as ParseUser;
      var queryBuilder = QueryBuilder<Goal>(Goal());
      queryBuilder.whereEqualTo('owner', user.objectId);
      // queryBuilder(['tasks']);
      ParseResponse response = await getAll(); // await queryBuilder.query();
      if (response.success) {
        return response.result;
      }
    } catch (error) {
      print(error);
    }
    return [];
  }

  // getUserGoalsHook() {
  //   return useFuture(useMemoized(() => getUserGoals()));
  // }

  @override
  save() async {
    ParseUser user = await ParseUser.currentUser() as ParseUser;
    ParseACL parseACL = ParseACL(owner: user);
    owner = user.objectId;
    setACL(parseACL);
    return await super.save();
  }

  Future addTask(Task task) async {
    if (task.objectId != null) {
      await task.save();
      var tasksRelation = getRelation('tasks');
      tasksRelation.add(task);
      tasks.add(task);
    } else {
      await task.save();
    }
  }
}
```

the call to get the list
```
  Future getList() async {
    print(await ParseObject('Task').getAll());
    print('hit 3');
    goals = await Goal().getUserGoals();
}
```

pubspec.yaml
```
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  parse_server_sdk: 1.0.25
  flutter_login: ^1.0.14
  intl: ^0.15.8
  http: ">=0.11.1 <0.13.0"
  provider: ^4.0.1
  flutter_hooks: ^0.7.0
  flutter_svg: ^0.1.1
  rxdart: ^0.23.1
  cached_network_image: ^2.0.0
  datetime_picker_formfield: ^1.0.0
  dropdown_formfield: ^0.1.1
  shared_preferences: ^0.5.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.4"
  build_runner: ^1.0.0
```

Even calling print(await Parse().healthCheck()); doesn't return anyhting.

The above code is just an example of what I'm trying. Not sure why it doesn't work. It did work at one point and then it stopped working for no reason. I got it to work the first time by playing with the curl commands in the terminal. I tried that again, but it didn't work. Anything I'm missing?
