### ISSUE TITLE
The getter 'debug' was called on null.

### ISSUE THREAD

**Issue by aBuder** [parse-community/Parse-SDK-Flutter#572]
I have a problem, that I can't create a new ParseObject in unit tests. If I call `BodyData bodyData = BodyData();` I got the following exception. 

How I can create new ParseObject in Unit tests? With previous version 1.10.0 it worked.

pubspec.yaml
```yaml
name: butterfly
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^2.2.3
  percent_indicator: ^2.1.4
  intl: ^0.16.1
  fl_chart: ^0.12.0
  timeline_tile: ^0.1.2
  bloc: ^6.1.1
  flutter_bloc: ^6.1.1
  date_utils: ^0.1.0+3
  parse_server_sdk: ^2.1.0
  shared_preferences: ^0.5.8
  mockito:
  url_launcher: 5.7.10
  iban: 0.2.0
  flutter_youtube: ^2.0.0+1
  flutter_picker: ^1.1.5
  numberpicker: ^1.3.0
  lottie: ^0.7.0+1
  http: ^0.12.2
  cached_network_image: ^2.5.0
  very_good_analysis: ^1.0.4
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  add_2_calendar: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.1.0
  network_image_mock: ^1.0.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - animations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

```log

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building BodyDataCreateContentView:
The getter 'debug' was called on null.
Receiver: null
Tried calling: debug

The relevant error-causing widget was:
  BodyDataCreateContentView
  file:///Users/abuder/projects/test/app/lib/screens/body_data_create_screen/body_data_create_screen.dart:19:16

When the exception was thrown, this was the stack:
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      isDebugEnabled (package:parse_server_sdk/src/utils/parse_utils.dart:8:47)
#2      new ParseObject (package:parse_server_sdk/src/objects/parse_object.dart:17:14)
#3      new BodyData (package:butterfly/model/model.dart:670:16)
#4      new BodyDataCreateCubit (package:butterfly/screens/body_data_create_screen/cubit/body_data_create_cubit.dart:11:23)
#5      BodyDataCreateScreen.build.<anonymous closure> (package:butterfly/screens/body_data_create_screen/body_data_create_screen.dart:15:30)
#6      _CreateInheritedProviderState.value (package:provider/src/inherited_provider.dart:646:35)
#7      _InheritedProviderScopeElement.value (package:provider/src/inherited_provider.dart:509:33)
#8      Provider.of (package:provider/src/provider.dart:287:29)
#9      ReadContext.read (package:provider/src/provider.dart:614:21)
#10     _BlocConsumerState.initState (package:flutter_bloc/src/bloc_consumer.dart:114:38)
```

```dart
class BodyDataCreateCubit extends Cubit<BodyDataCreateState> {
  final BodyDataRepository bodyDataRepository;
  BodyData bodyData = BodyData();

  BodyDataCreateCubit({
    @required this.bodyDataRepository,
  }) : super(BodyDataCreateInitialState());

  Future<void> load() async {
    try {
      BodyData lastBodyData = await bodyDataRepository.fetchLast();
      bodyData = BodyData.copy(lastBodyData);
      emit(BodyDataCreateUpdateState(
        bodyData: bodyData,
      ));
    } catch (ex) {
      emit(BodyDataCreateErrorState(
        bodyData: bodyData,
      ));
    }
  }
}
```

```dart

/// Model class for Equipment
class BodyData extends ParseObject implements ParseCloneable {
  BodyData() : super('BodyData');

  BodyData.clone() : this();

  /// Looks strangely hacky but due to Flutter not using reflection, we have to
  /// mimic a clone
  @override
  clone(Map map) => BodyData.clone()..fromJson(map);

  num get size => get<num>('size');

  set size(num value) => set<num>('size', value);

  num get weight => get<num>('weight');

  set weight(num value) => set<num>('weight', value);

  num get fat => get<num>('fat');

  set fat(num value) => set<num>('fat', value);

  num get rate => get<num>('rate');

  set rate(num value) => set<num>('rate', value);

  num get pressure => get<num>('pressure');

  set pressure(num value) => set<num>('pressure', value);

  num get chest => get<num>('chest');

  set chest(num value) => set<num>('chest', value);

  num get abdomen => get<num>('abdomen');

  set abdomen(num value) => set<num>('abdomen', value);

  num get leg => get<num>('leg');

  set leg(num value) => set<num>('leg', value);

  num get hip => get<num>('hip');

  set hip(num value) => set<num>('hip', value);

  num get arm => get<num>('arm');

  set arm(num value) => set<num>('arm', value);

  num get pwc => get<num>('pwc');

  set pwc(num value) => set<num>('pwc', value);

  num get diastole => get<num>('diastole');

  set diastole(num value) => set<num>('diastole', value);

  num get muscle => get<num>('muscle');

  set muscle(num value) => set<num>('muscle', value);

  num get water => get<num>('water');

  set water(num value) => set<num>('water', value);

  factory BodyData.copy(BodyData bodyData) {
    final copyBodyData = BodyData();
    copyBodyData.weight = bodyData.weight;
    copyBodyData.diastole = bodyData.diastole;
    copyBodyData.water = bodyData.water;
    copyBodyData.muscle = bodyData.muscle;
    copyBodyData.leg = bodyData.leg;
    copyBodyData.chest = bodyData.chest;
    copyBodyData.pressure = bodyData.pressure;
    copyBodyData.size = bodyData.size;
    copyBodyData.pwc = bodyData.pwc;
    copyBodyData.arm = bodyData.arm;
    copyBodyData.hip = bodyData.hip;
    copyBodyData.abdomen = bodyData.abdomen;
    copyBodyData.rate = bodyData.rate;
    copyBodyData.fat = bodyData.fat;
    return copyBodyData;
  }
}
```
