### ISSUE TITLE
Upgrade package dependencies

### ISSUE THREAD

**Issue by JTPenn-EG** [parse-community/Parse-SDK-Flutter#591]
I cannot use the plugin alongside many packages because it depends on older versions of some other packages
Example: I cannot use latest version of google_fonts and parse_server because parse depends on older version of http. (there are also some conflicts with many other packages).

**Comment by RodrigoSMarques** [comment]
There is a fixed issue about this problem.

But you can check here:

#541 a #573

**Comment by JTPenn-EG** [comment]
> There is a fixed issue about this problem.
> 
> But you can check here:
> 
> #541 a #573

Thank you, works good.
I haven't tested all parse features, but so far so good!

**Comment by wangbo4020** [comment]
Could upgrade to
```yaml
meta: ^1.3.0
mime_type: ^1.0.0
dio: ^4.0.0
http: ^0.13.0
path: ^1.8.0
sembast: ^3.0.0
sembast_web: ^2.0.0
uuid: ^3.0.0
xxtea: ^2.1.0
web_socket_channel: ^2.0.0
```
