### ISSUE TITLE
I am not able to connect via Flutter to my local parse-server

### ISSUE THREAD

**Issue by Vildnex** [parse-community/Parse-SDK-Flutter#706]
### New Issue Checklist
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Flutter SDK](https://github.com/parse-community/Parse-SDK-Flutter/releases). 

### Issue Description
I am starting my local parse-server via docker-compose file by running `docker-compose up` on the fallowing file:
```

version: '3.9'

services:
  database:
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - data_volume:/data/mongodb

  server:
    restart: always
    image: parseplatform/parse-server:4.10.4
    ports:
      - 1337:1337
    environment:
      - PARSE_SERVER_APPLICATION_ID=COOK_APP
      - PARSE_SERVER_MASTER_KEY=MASTER_KEY_1
      - PARSE_SERVER_CLIENT_KEY=CLIENT_KEY_1
      - PARSE_SERVER_DATABASE_URI=mongodb://admin:admin@mongo/parse_server?authSource=admin
      - PARSE_ENABLE_CLOUD_CODE=yes
    links:
      - database:mongo
    volumes:
      - data_volume:/data/server
      - ./../lib/core/database/parse_server/cloud:/parse-server/cloud

  dashboard:
    image: parseplatform/parse-dashboard:4.0.0
    ports:
      - "4040:4040"
    depends_on:
      - server
    environment:
      - PARSE_DASHBOARD_APP_ID=COOK_APP
      - PARSE_DASHBOARD_MASTER_KEY=MASTER_KEY_1
      - PARSE_DASHBOARD_USER_ID=admin
      - PARSE_DASHBOARD_USER_PASSWORD=admin
      - PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=true
      - PARSE_DASHBOARD_SERVER_URL=http://localhost:1337/parse
    volumes:
      - data_volume:/data/dashboard

volumes:
  data_volume:
    driver: local
```
Then I am running my Flutter code:

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  const keyApplicationId = 'COOK_APP';
  const keyClientKey = 'CLIENT_KEY_1';
  const keyParseServerUrl = 'http://localhost:1337/parse';

  var response = await Parse().initialize(keyApplicationId, keyParseServerUrl,
      clientKey: keyClientKey, autoSendSessionId: true);
  var connRes = await response.healthCheck();
  var s = connRes.error?.message ?? "";
  print("ERROR:" + s);
  var firstObject = ParseObject('FirstClass')
    ..set(
        'message', 'Hey ! First message from Flutter. Parse is now connected');
  await firstObject.save();

  print('done');
}
```
Which is going to give me this error message:

`SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = localhost, port = 48026`

I think that might be a problem with setting up the client-key on my parse-server because if I am trying with all the right keys from Back4App everything works properly, but with my local version, not.

Am I missing something? 

Parse Flutter SDK
- SDK version: `3.1.0`
- Operating system version: `ubuntu 21.10 and manjaro 21.2.4 `

Server
- Parse Server version: `4.10.4`
