### ISSUE TITLE
Flutter can not connect to the parse-server via parse_server_sdk_flutter

### ISSUE THREAD

**Issue by Vildnex** [parse-community/Parse-SDK-Flutter#707]
### New Issue Checklist
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest version of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Flutter SDK](https://github.com/parse-community/Parse-SDK-Flutter/releases). 

### Issue Description
I am trying to connect my flutter application via parse-server using `parse_server_sdk_flutter` and it get the following error will trying to do that `Exception: SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = localhost, port = 39234`

### Steps to reproduce
I have the following `docker-compose.yml` file which will be run via `docker-compose up`:
```
version: '3.9'

services:
  database:
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - data_volume:/data/mongodb

  server:
    restart: always
    image: parseplatform/parse-server:4.10.4
    ports:
      - 1337:1337
    environment:
      - PARSE_SERVER_APPLICATION_ID=COOK_APP
      - PARSE_SERVER_MASTER_KEY=MASTER_KEY_1
      - PARSE_SERVER_DATABASE_URI=mongodb://admin:admin@mongo/parse_server?authSource=admin
      - PARSE_ENABLE_CLOUD_CODE=yes
    links:
      - database:mongo
    volumes:
      - data_volume:/data/server
      - ./../lib/core/database/parse_server/cloud:/parse-server/cloud

  dashboard:
    image: parseplatform/parse-dashboard:4.0.0
    ports:
      - "4040:4040"
    depends_on:
      - server
    environment:
      - PARSE_DASHBOARD_APP_ID=COOK_APP
      - PARSE_DASHBOARD_MASTER_KEY=MASTER_KEY_1
      - PARSE_DASHBOARD_USER_ID=admin
      - PARSE_DASHBOARD_USER_PASSWORD=admin
      - PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=true
      - PARSE_DASHBOARD_SERVER_URL=http://localhost:1337/parse
    volumes:
      - data_volume:/data/dashboard

volumes:
  data_volume:
    driver: local
```
And I also have my flutter code:

```
import 'package:flutter/material.dart';
import 'package:parse_server_sdk_flutter/parse_server_sdk.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  const keyApplicationId = "COOK_APP";
  const keyMasterKey = 'MASTER_KEY_1';
  const keyParseServerUrl = "http://localhost:1337/parse";

  await Parse().initialize(keyApplicationId, keyParseServerUrl, masterKey: keyMasterKey, debug: true);
  var firstObject = ParseObject('FirstClass')
    ..set('message', 'Hey ! First message from Flutter. Parse is now connected');
  await firstObject.save();
}
```

### Actual Outcome
Every single time when I am trying to run this flutter code I am getting the same output
```
I/flutter ( 5881): ╭-- Parse Request
I/flutter ( 5881): curl -X POST -H 'content-type: text/plain; charset=utf-8' -H 'user-agent: Flutter Parse SDK 3.1.0' -H 'X-Parse-Application-Id: COOK_APP' -H 'X-Parse-Master-Key: MASTER_KEY_1' -d '{"message":"Hey ! First message from Flutter. Parse is now connected"}' http://localhost:1337/parse/classes/FirstClass
I/flutter ( 5881): 
I/flutter ( 5881):  http://localhost:1337/parse/classes/FirstClass
I/flutter ( 5881): ╰--
I/flutter ( 5881): ╭-- Parse Response
I/flutter ( 5881): Class: FirstClass
I/flutter ( 5881): Function: ParseApiRQ.create
I/flutter ( 5881): Status Code: -1
I/flutter ( 5881): Type: UnknownError
I/flutter ( 5881): Exception: SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = localhost, port = 39240
I/flutter ( 5881): ╰-- 
I/flutter ( 5881):  

```
### Expected Outcome
But if I am going to copy-paste the command that it should get executed via the `save` function and run in terminal:
`curl -X POST -H 'content-type: text/plain; charset=utf-8' -H 'user-agent: Flutter Parse SDK 3.1.0' -H 'X-Parse-Application-Id: COOK_APP' -H 'X-Parse-Master-Key: MASTER_KEY_1' -d '{"message":"Hey ! First message from Flutter. Parse is now connected"}' http://localhost:1337/parse/classes/FirstClass`

I will get a successful execution and my FirstClass will be created with success, the output been:
`{"objectId":"JmXO1068kJ","createdAt":"2022-03-04T22:20:35.040Z"}`

### Environment
Flutter: `2.10.3`
Dart: `2.16.1`
DevTools: `2.9.2`

Parse Flutter SDK
- SDK version: `3.1.0`
- Operating system version: `Manjaro 21.2.4`

Server
- Parse Server version: `4.10.4`
- MongoDB:`5.0`
