### ISSUE TITLE
Sdk for web

### ISSUE THREAD

**Issue by alex9153** [parse-community/Parse-SDK-Flutter#781]
Hi. 

I need very much parse sdk for web

**Comment by RodrigoSMarques** [comment]
pub.dev does not display the web support label.  But, read the documentation that explains exactly what is needed to run on the web.

**Comment by mtrezza** [comment]
Should we indicate that somewhere in our README maybe?

**Comment by RodrigoSMarques** [comment]
[Web Support](https://github.com/parse-community/Parse-SDK-Flutter/tree/master/packages/flutter#web-support)

![Captura de Tela 2022-08-30 às 21 46 19](https://user-images.githubusercontent.com/17687286/187568780-bfaa6541-4cdd-4fb6-b5c7-5051bb0a8a41.png)

**Comment by RodrigoSMarques** [comment]
> I've seen some Flutter SDKs that show for example 3 icons at the top of their docs to indicate which platforms they support:
> 
> * iOS
> * Android
> * Web

Yes.  But for some reason pub.dev doesn't identify support in the Parse package.

In fact, the reason is here.

![Captura de Tela 2022-09-01 às 10 48 24](https://user-images.githubusercontent.com/17687286/187930769-9b8335e8-25a9-47c9-9a69-c2540280877f.png)

It's the way he identifies platform support.
In practice support already exists even before Flutter Web is stable.
For this reason, information was placed right at the beginning of the documentation.

**Comment by mtrezza** [comment]
How can we get Flutter display Web compatibility?

**Comment by RodrigoSMarques** [comment]
> How can we get Flutter display Web compatibility?

The analysis instructs to remove the import (`dart:o`) from a class, but if this is executed the code doesn't work.
Even with this import, the code runs on the web.

I don't know what can be done.

**Comment by mtrezza** [comment]
Do you know why `dart.io` is considered an issue here? I assume there is a reason for that.

**Comment by mbfakourii** [comment]
You can skip this pub.dev error with the following code!

Add the following code at the end of ```pubspec.yaml``` package

```
flutter:
  plugin:
    platforms:
      android:
        default_package: parse_server_sdk_flutter
      ios:
        default_package: parse_server_sdk_flutter
      linux:
        default_package: parse_server_sdk_flutter
      macos:
        default_package: parse_server_sdk_flutter
      web:
        default_package: parse_server_sdk_flutter
      windows:
        default_package: parse_server_sdk_flutter
```

by doing this, you are indicating that this package works for these platforms
